### ISSUE TITLE
Pipeline warning.

### ISSUE THREAD

**Issue by A-Rai-col** [donalfenwick/azuredevops-promote-artifact-version#1]
Currently seeing this warning in my pipelines when using `promote-artifact-version@1` task. 

```
##[warning]Task 'Promote artifact version' version 1 (promote-artifact-version@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
```

**Comment by donalfenwick** [comment]
Hi @A-Rai-col,

Thanks for bringing it to my attention. Have updated the config to support node 20 and tested it out.
New version is now published to the marketplace.

**Comment by donalfenwick** [comment]
new version added
